name: Cloud-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cloud-CI cozyboard_2023
      run: |
        sudo apt-get update
        sudo apt-get install libudev1 libudev-dev
        ARM_TOOLCHAIN_VERSION=$(curl -s https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads | grep -Po '<h4>Version \K.+(?=</h4>)')
        curl -Lo gcc-arm-none-eabi.tar.xz "https://developer.arm.com/-/media/Files/downloads/gnu/${ARM_TOOLCHAIN_VERSION}/binrel/arm-gnu-toolchain-${ARM_TOOLCHAIN_VERSION}-x86_64-arm-none-eabi.tar.xz"
        sudo mkdir /opt/gcc-arm-none-eabi
        sudo tar xf gcc-arm-none-eabi.tar.xz --strip-components=1 -C /opt/gcc-arm-none-eabi
        echo 'export PATH=$PATH:/opt/gcc-arm-none-eabi/bin' | sudo tee -a /etc/profile.d/gcc-arm-none-eabi.sh
        source /etc/profile
        rm -rf gcc-arm-none-eabi.tar.xz
        sudo apt install libclang-dev
        sudo apt install clang
        sudo rm /home/runner/.cargo/bin/rust-analyzer
        sudo rm /home/runner/.cargo/bin/rustfmt
        sudo rm /home/runner/.cargo/bin/cargo-fmt
        rustup install nightly-2023-10-02
        rustup install 1.73.0
        rustup target add thumbv7em-none-eabi
        rustup target add thumbv7em-none-eabi --toolchain nightly-2023-10-02
        rustup component add rustfmt
        rustup component add rustfmt --toolchain nightly-2023-10-02-x86_64-unknown-linux-gnu
        rustup component add clippy --toolchain nightly-2023-10-02-x86_64-unknown-linux-gnu
        rustup show
        cargo clippy
        cargo test
        cargo build
